apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rich-text-renderer-java 
  description: Java library for Rich Text API. It helps in easily rendering rich text stored in Contentful using Java.
  annotations:
    github.com/project-slug: contentful/rich-text-renderer-java 
    contentful.com/service-tier: '4'
  tags:
    - tier-4
spec:
  type: library
  lifecycle: production
  owner: group:team-developer-experience
